"""baseline schema

Revision ID: efe2cc0f2c21
Revises: 
Create Date: 2026-07-12 04:32:10.154772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe2cc0f2c21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('circuit_breaker_state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mirrored_records',
    sa.Column('store', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('updated_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('store', 'key')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('entry_ts', sa.Integer(), nullable=False),
    sa.Column('updated_ts', sa.Integer(), nullable=False),
    sa.Column('greeks_json', sa.Text(), nullable=True),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('slippage_bps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('mirrored_records')
    op.drop_table('equity_snapshots')
    # ### end Alembic commands ###
