"""Generate the SterlingV2 authoritative baseline report from real parquet.

Baseline = the 5 long-only edge signals, all symbols, 1h+4h, Intraday profile
(SL 2.0xATR / TP 3.5xATR), run through the leak-free harness (next-bar-open
fills, 5bps slippage, 0.10% round-trip fee, realized-frequency Sharpe).

This is the SOLE source of truth for "where we start": every lever in Phase 3+
is judged against these numbers on an untouched test slice. It deliberately does
NOT read any pre-existing .md report. Writes docs/sterling_v2/baseline_report.md.
"""
import os
import sys
import warnings

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
warnings.filterwarnings("ignore")  # silence pandas bool-invert deprecation in edge sigs

from app.engines.sterling_v2 import data as D, harness as H
from app.engines.sterling_v2.config import SimConfig
from app.engines.edge.strategies import SIGNAL_FNS

STRATS = ["ma_crossover", "breakout", "smc", "price_action", "mean_reversion"]
TFS = ["1h", "4h"]
cfg = SimConfig(sl_mult=2.0, tp_mult=3.5, fee_round_trip=0.001, slippage=0.0005)


def main() -> None:
    rows = []
    for sym, path in D.list_symbols().items():
        df = D.load_symbol(path)
        for tf in TFS:
            d = D.resample_tf(df, tf)
            for s in STRATS:
                m = H.compute_metrics(H.simulate(d, SIGNAL_FNS[s](d), None, cfg))
                rows.append((sym, tf, s, m))

    lines = [
        "# SterlingV2 Baseline (harness-generated, long-only)",
        "",
        "Generated by `backend/scratch/v2_baseline.py` directly from the real parquet",
        "vector stores. Cost model: 0.10% round-trip fee, 5bps slippage/fill, next-bar-open",
        "fills, ATR(14) stops/targets (SL 2.0x / TP 3.5x), Sharpe annualized by realized",
        "trade frequency. This table is the authoritative starting point for all levers.",
        "",
        "| Symbol | TF | Strategy | Trades | Win% | PF | Sharpe | Net% | MaxDD% |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for sym, tf, s, m in rows:
        lines.append(
            f"| {sym} | {tf} | {s} | {m['trades']} | {m['win']*100:.1f} | "
            f"{m['pf']:.2f} | {m['sharpe']:.2f} | {m['net']*100:+.1f} | "
            f"{m['max_dd']*100:.1f} |"
        )

    out = os.path.abspath(
        os.path.join(D.parquet_dir(), "..", "docs", "sterling_v2", "baseline_report.md")
    )
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", out)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
