import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles/globals.css';
import './styles/performanceOverrides.css';
import './styles/kiteSignalTypography.css';
import { App } from './App';
import { installKiteDefaultPreferences } from './utils/kiteDefaultPreferences';
import { installScrollAutohide } from './utils/scrollAutohide';
import { installKiteChartTimezone } from './utils/kiteChartTimezone';
import { installTradingViewPalette } from './utils/tradingViewPalette';